### PR TITLE
compatible with nim 1.x

### PR DESCRIPTION
**Pull request by xyb**

### CODE REVIEW

**Comment by boydgreenfield** [comment]
This looks reasonable to me, but it seems like this would also be a good opportunity to add GH actions for the tests (and consider renaming the repo to `nim-bloom`... 😬)

I'll try to find time this week to do this (and would of course happily accept an extra commit on this PR).

**Comment by xyb** [comment]
@boydgreenfield I have set up the CI using Github Actions. It also builds and publishes the documentation to Github Pages once you set the Github Pages' theme in the repo settings page.

**Comment by xyb** [comment]
Here is the result of Github Actions: https://github.com/xyb/nimrod-bloom/runs/880657615?check_suite_focus=true

**Comment by xyb** [comment]
And the url of automatically compiled document is: https://xyb.github.io/nimrod-bloom/

**Comment by boydgreenfield** [comment]
This is great, thanks @xyb. Merging this now, and thanks again for the help!

**Pull request merged**
